### ISSUE TITLE
Take multiple topic files 

### ISSUE THREAD

**Issue by elshize** [pisa-engine/standard-benchmark#9]
Like so:
```
runs:
    - collection: wapo
      type: evaluate
      topics:
        - /data/collections/WashingtonPost.v2/topics.core18.txt
        - /data/collections/WashingtonPost.v2/topics.core18.txt
      qrels:
        - /data/collections/WashingtonPost.v2/qrels.core18.txt
        - /data/collections/WashingtonPost.v2/qrels.core18.txt
      output: wapo.trec
```
